!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers:
- mHandle: 212
  mName: SPI NavX X Accel
  mType: com.snobot.simulator.module_wrapper.BaseAccelerometerWrapper
- mHandle: 213
  mName: SPI NavX Y Accel
  mType: com.snobot.simulator.module_wrapper.BaseAccelerometerWrapper
- mHandle: 214
  mName: SPI NavX Z Accel
  mType: com.snobot.simulator.module_wrapper.BaseAccelerometerWrapper
mAnalogIn:
- mHandle: 0
  mName: pressureSensor
  mType: com.snobot.simulator.module_wrapper.wpi.WpiAnalogInWrapper
- mHandle: 1
  mName: liftPot
  mType: com.snobot.simulator.module_wrapper.wpi.WpiAnalogInWrapper
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers:
  4: NavX
mDigitalIO:
- mHandle: 0
  mName: Digital IO 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 1
  mName: Digital IO 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 2
  mName: Digital IO 2
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 3
  mName: Digital IO 3
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
mEncoders:
- mConnectedSpeedControllerHandle: 101
  mHandle: 0
  mName: leftEncoder
  mType: com.snobot.simulator.module_wrapper.wpi.WpiEncoderWrapper
- mConnectedSpeedControllerHandle: 100
  mHandle: 1
  mName: rightEncoder
  mType: com.snobot.simulator.module_wrapper.wpi.WpiEncoderWrapper
mGyros:
- mHandle: 212
  mName: SPI NavX Yaw
  mType: com.snobot.simulator.module_wrapper.BaseGyroWrapper
- mHandle: 213
  mName: SPI NavX Pitch
  mType: com.snobot.simulator.module_wrapper.BaseGyroWrapper
- mHandle: 214
  mName: SPI NavX Roll
  mType: com.snobot.simulator.module_wrapper.BaseGyroWrapper
mPwm:
- mHandle: 4
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 1.0
  mName: liftMotor
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 100
  mMotorModelConfig:
    mGearReduction: 10.75
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 2
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.GravityLoadMotorSimulationConfig
    mLoad: 60.0
  mName: rightDriveMotor0
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 101
  mMotorModelConfig:
    mGearReduction: 10.75
    mGearboxEfficiency: 1.0
    mHasBrake: false
    mInverted: false
    mMotorType: CIM
    mNumMotors: 2
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.GravityLoadMotorSimulationConfig
    mLoad: 60.0
  mName: leftDriveMotor0
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 102
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: rightDrivieMotor1
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 103
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: leftDriveMotor1
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
mRelays: []
mSimulatorComponents: []
mSolenoids:
- mHandle: 0
  mName: clawOpen
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 1
  mName: clawClose
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
